#!/bin/bash
set -e

MODELS_DIR="/models"
CONFIG_FILE="/opt/ComfyUI/extra_model_paths.yaml"

# ComfyUI model type mappings - maps common directory names to ComfyUI types
declare -A MODEL_TYPE_MAP=(
    ["checkpoints"]="checkpoints"
    ["checkpoint"]="checkpoints"
    ["ckpt"]="checkpoints"
    ["diffusion_models"]="diffusion_models"
    ["diffusion"]="diffusion_models"
    ["dit"]="diffusion_models"
    ["unet"]="diffusion_models"
    ["vae"]="vae"
    ["vaes"]="vae"
    ["text_encoders"]="text_encoders"
    ["text_encoder"]="text_encoders"
    ["clip"]="clip"
    ["clip_vision"]="clip_vision"
    ["loras"]="loras"
    ["lora"]="loras"
    ["controlnet"]="controlnet"
    ["controlnets"]="controlnet"
    ["embeddings"]="embeddings"
    ["embedding"]="embeddings"
    ["upscale_models"]="upscale_models"
    ["upscale"]="upscale_models"
    ["esrgan"]="upscale_models"
    ["hypernetworks"]="hypernetworks"
    ["configs"]="configs"
    ["reprompt"]="text_encoders"
)

generate_model_paths() {
    echo "# Auto-generated by entrypoint.sh at $(date)"
    echo "# Scanning $MODELS_DIR for model collections"
    echo ""

    # Check if models directory exists and has content
    if [[ ! -d "$MODELS_DIR" ]] || [[ -z "$(ls -A "$MODELS_DIR" 2>/dev/null)" ]]; then
        echo "# No models found in $MODELS_DIR"
        return
    fi

    # Iterate through each model collection (top-level directory in /models)
    for collection_path in "$MODELS_DIR"/*/; do
        [[ -d "$collection_path" ]] || continue

        collection_name=$(basename "$collection_path")
        # Skip hidden directories
        [[ "$collection_name" == .* ]] && continue

        # Sanitize collection name for YAML key (replace special chars with underscores)
        yaml_key=$(echo "$collection_name" | tr '-' '_' | tr ' ' '_' | tr '.' '_')

        echo "${yaml_key}:"
        echo "    base_path: ${collection_path}"

        # Scan for known model type subdirectories
        found_types=false
        for subdir in "$collection_path"/*/; do
            [[ -d "$subdir" ]] || continue

            subdir_name=$(basename "$subdir")
            subdir_lower=$(echo "$subdir_name" | tr '[:upper:]' '[:lower:]')

            # Check if this directory name maps to a ComfyUI model type
            if [[ -n "${MODEL_TYPE_MAP[$subdir_lower]}" ]]; then
                comfyui_type="${MODEL_TYPE_MAP[$subdir_lower]}"
                echo "    ${comfyui_type}: ${subdir_name}/"
                found_types=true
            fi
        done

        # If no recognized subdirs, check if there are model files directly in collection
        if [[ "$found_types" == false ]]; then
            # Check for common model file extensions
            if ls "$collection_path"/*.safetensors &>/dev/null || \
               ls "$collection_path"/*.ckpt &>/dev/null || \
               ls "$collection_path"/*.pt &>/dev/null || \
               ls "$collection_path"/*.pth &>/dev/null; then
                echo "    checkpoints: ./"
            fi
        fi

        echo ""
    done
}

echo "=== ComfyUI Entrypoint ==="
echo "Generating model paths configuration..."

# Generate the config file
generate_model_paths > "$CONFIG_FILE"

echo "Generated $CONFIG_FILE:"
cat "$CONFIG_FILE"
echo ""
echo "=== Starting ComfyUI ==="

# Execute the main command
exec "$@"
